name: Discord
on:
  workflow_call:
    secrets:
      webhook:
        description: 'Discord webhook'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      - run: npm install axios
      - name: Notes 📝
        id: notes
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const axios = require('axios');

            notes = context.payload.release.body

            // replace all non-supported characters
            notes = notes.replaceAll('###', '')
            notes = notes.trim()

            const options = {
              method: 'POST',
              url: "${{ secrets.webhook }}",
              headers: { 'Content-Type': 'application/json' },
              data: { content: notes }
            };

            axios
              .request(options)
              .then(() => {
                core.info('Message was sent successfully');
              });
